<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-07T18:44:17 IST" name="Suite" finished-at="2025-03-07T18:44:20 IST" duration-ms="2959">
    <groups>
    </groups>
    <test started-at="2025-03-07T18:44:17 IST" name="ChromeTest" finished-at="2025-03-07T18:44:17 IST" duration-ms="35">
    </test> <!-- ChromeTest -->
    <test started-at="2025-03-07T18:44:17 IST" name="EdgeTest" finished-at="2025-03-07T18:44:20 IST" duration-ms="2846">
      <class name="test.TC_002LoginTest">
        <test-method is-config="true" signature="reportIniatialization()[pri:0, instance:test.TC_002LoginTest@279fedbd]" started-at="2025-03-07T18:44:16 IST" name="reportIniatialization" finished-at="2025-03-07T18:44:17 IST" duration-ms="911" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportIniatialization -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.TC_002LoginTest@279fedbd]" started-at="2025-03-07T18:44:17 IST" name="setup" finished-at="2025-03-07T18:44:17 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="testDetails()[pri:0, instance:test.TC_002LoginTest@279fedbd]" started-at="2025-03-07T18:44:17 IST" name="testDetails" finished-at="2025-03-07T18:44:17 IST" duration-ms="24" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDetails -->
        <test-method signature="loginTest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:test.TC_002LoginTest@279fedbd]" started-at="2025-03-07T18:44:17 IST" name="loginTest" data-provider="readData" finished-at="2025-03-07T18:44:20 IST" duration-ms="2767" status="FAIL">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
[public void test.TC_002LoginTest.loginTest(java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: loginTest([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2])
Arguments: [(java.lang.String) Leema12345@gmail.com,(java.lang.String) Leema.12345,(java.lang.String) ValidEmailValidPassword,(java.lang.String) Leema12345@gmail.com]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void test.TC_002LoginTest.loginTest(java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: loginTest([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2])
Arguments: [(java.lang.String) Leema12345@gmail.com,(java.lang.String) Leema.12345,(java.lang.String) ValidEmailValidPassword,(java.lang.String) Leema12345@gmail.com]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:909)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:37)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="reportClose()[pri:0, instance:test.TC_002LoginTest@279fedbd]" started-at="2025-03-07T18:44:20 IST" name="reportClose" finished-at="2025-03-07T18:44:21 IST" duration-ms="1097" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportClose -->
      </class> <!-- test.TC_002LoginTest -->
    </test> <!-- EdgeTest -->
  </suite> <!-- Suite -->
</testng-results>
